version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        environment:
            - PORT=3000
            - POSTGRES_HOST=db
            - POSTGRES_PORT=5432
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DATABASE=curveimator
        depends_on:
            - db
    db:
        image: postgres:13-alpine
        container_name: postgres_db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: curveimator
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
volumes:
    postgres_data:
