name: curveimator-test
services:
    app-test:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3001:3000"
        environment:
            - HOST=localhost
            - PORT=3000
            - POSTGRES_HOST=db
            - POSTGRES_PORT=5433
            - POSTGRES_USER=test_postgres
            - POSTGRES_PASSWORD=test_postgres
            - POSTGRES_DATABASE=test_curveimator
        depends_on:
            - db-test
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
    db-test:
        image: postgres:13-alpine
        container_name: test_postgres_db
        environment:
            POSTGRES_USER: test_postgres
            POSTGRES_PASSWORD: test_postgres
            POSTGRES_DB: test_curveimator
        ports:
            - "5433:5432"
        volumes:
            - test_postgres_data:/var/lib/postgresql/test_data
volumes:
    test_postgres_data:
